version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: raccommode-freetube_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"
  web:
    image: ghcr.io/linuxserver/freetube:version-197897083@sha256:5442391cfb9bd3c4d50266a545281ae21a76ffee6f61f1c236d78d1a16ace124
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/config:rw
    environment:
     CUSTOM_USER: admin
     PASSWORD: umbrel
     TZ: Europe/Berlin
     PUID: 1000
     PGID: 1000